// Office avatar manifest for Jinn/Cuttlefish — only icons assigned to employees.
// PNGs live under packages/web/public/avatars/office/{64,128,256,512}/.
// Vite serves them at /avatars/office/<size>/<id>.png

export interface OfficeAvatar {
  id: string
  label: string
  path: string
  path64: string
  path128: string
  path256: string
  path512: string
}

export const OFFICE_AVATARS = [
  { id: "backpack",            label: "Backpack",            path: "/avatars/office/128/backpack.png",            path64: "/avatars/office/64/backpack.png",            path128: "/avatars/office/128/backpack.png",            path256: "/avatars/office/256/backpack.png",            path512: "/avatars/office/512/backpack.png" },
  { id: "binder_clip",         label: "Binder Clip",         path: "/avatars/office/128/binder_clip.png",         path64: "/avatars/office/64/binder_clip.png",         path128: "/avatars/office/128/binder_clip.png",         path256: "/avatars/office/256/binder_clip.png",         path512: "/avatars/office/512/binder_clip.png" },
  { id: "blackboard",          label: "Blackboard",          path: "/avatars/office/128/blackboard.png",          path64: "/avatars/office/64/blackboard.png",          path128: "/avatars/office/128/blackboard.png",          path256: "/avatars/office/256/blackboard.png",          path512: "/avatars/office/512/blackboard.png" },
  { id: "calculator",          label: "Calculator",          path: "/avatars/office/128/calculator.png",          path64: "/avatars/office/64/calculator.png",          path128: "/avatars/office/128/calculator.png",          path256: "/avatars/office/256/calculator.png",          path512: "/avatars/office/512/calculator.png" },
  { id: "calendar",            label: "Calendar",            path: "/avatars/office/128/calendar.png",            path64: "/avatars/office/64/calendar.png",            path128: "/avatars/office/128/calendar.png",            path256: "/avatars/office/256/calendar.png",            path512: "/avatars/office/512/calendar.png" },
  { id: "clipboard_checklist", label: "Clipboard Checklist", path: "/avatars/office/128/clipboard_checklist.png", path64: "/avatars/office/64/clipboard_checklist.png", path128: "/avatars/office/128/clipboard_checklist.png", path256: "/avatars/office/256/clipboard_checklist.png", path512: "/avatars/office/512/clipboard_checklist.png" },
  { id: "computer_monitor",    label: "Computer Monitor",    path: "/avatars/office/128/computer_monitor.png",    path64: "/avatars/office/64/computer_monitor.png",    path128: "/avatars/office/128/computer_monitor.png",    path256: "/avatars/office/256/computer_monitor.png",    path512: "/avatars/office/512/computer_monitor.png" },
  { id: "corded_phone",        label: "Corded Phone",        path: "/avatars/office/128/corded_phone.png",        path64: "/avatars/office/64/corded_phone.png",        path128: "/avatars/office/128/corded_phone.png",        path256: "/avatars/office/256/corded_phone.png",        path512: "/avatars/office/512/corded_phone.png" },
  { id: "crayon",              label: "Crayon",              path: "/avatars/office/128/crayon.png",              path64: "/avatars/office/64/crayon.png",              path128: "/avatars/office/128/crayon.png",              path256: "/avatars/office/256/crayon.png",              path512: "/avatars/office/512/crayon.png" },
  { id: "desk_lamp",           label: "Desk Lamp",           path: "/avatars/office/128/desk_lamp.png",           path64: "/avatars/office/64/desk_lamp.png",           path128: "/avatars/office/128/desk_lamp.png",           path256: "/avatars/office/256/desk_lamp.png",           path512: "/avatars/office/512/desk_lamp.png" },
  { id: "document_stack",      label: "Document Stack",      path: "/avatars/office/128/document_stack.png",      path64: "/avatars/office/64/document_stack.png",      path128: "/avatars/office/128/document_stack.png",      path256: "/avatars/office/256/document_stack.png",      path512: "/avatars/office/512/document_stack.png" },
  { id: "envelope",            label: "Envelope",            path: "/avatars/office/128/envelope.png",            path64: "/avatars/office/64/envelope.png",            path128: "/avatars/office/128/envelope.png",            path256: "/avatars/office/256/envelope.png",            path512: "/avatars/office/512/envelope.png" },
  { id: "eraser",              label: "Eraser",              path: "/avatars/office/128/eraser.png",              path64: "/avatars/office/64/eraser.png",              path128: "/avatars/office/128/eraser.png",              path256: "/avatars/office/256/eraser.png",              path512: "/avatars/office/512/eraser.png" },
  { id: "file_folder",         label: "File Folder",         path: "/avatars/office/128/file_folder.png",         path64: "/avatars/office/64/file_folder.png",         path128: "/avatars/office/128/file_folder.png",         path256: "/avatars/office/256/file_folder.png",         path512: "/avatars/office/512/file_folder.png" },
  { id: "filing_cabinet",      label: "Filing Cabinet",      path: "/avatars/office/128/filing_cabinet.png",      path64: "/avatars/office/64/filing_cabinet.png",      path128: "/avatars/office/128/filing_cabinet.png",      path256: "/avatars/office/256/filing_cabinet.png",      path512: "/avatars/office/512/filing_cabinet.png" },
  { id: "highlighter",         label: "Highlighter",         path: "/avatars/office/128/highlighter.png",         path64: "/avatars/office/64/highlighter.png",         path128: "/avatars/office/128/highlighter.png",         path256: "/avatars/office/256/highlighter.png",         path512: "/avatars/office/512/highlighter.png" },
  { id: "hole_punch",          label: "Hole Punch",          path: "/avatars/office/128/hole_punch.png",          path64: "/avatars/office/64/hole_punch.png",          path128: "/avatars/office/128/hole_punch.png",          path256: "/avatars/office/256/hole_punch.png",          path512: "/avatars/office/512/hole_punch.png" },
  { id: "in_tray",             label: "In Tray",             path: "/avatars/office/128/in_tray.png",             path64: "/avatars/office/64/in_tray.png",             path128: "/avatars/office/128/in_tray.png",             path256: "/avatars/office/256/in_tray.png",             path512: "/avatars/office/512/in_tray.png" },
  { id: "keyboard",            label: "Keyboard",            path: "/avatars/office/128/keyboard.png",            path64: "/avatars/office/64/keyboard.png",            path128: "/avatars/office/128/keyboard.png",            path256: "/avatars/office/256/keyboard.png",            path512: "/avatars/office/512/keyboard.png" },
  { id: "marker",              label: "Marker",              path: "/avatars/office/128/marker.png",              path64: "/avatars/office/64/marker.png",              path128: "/avatars/office/128/marker.png",              path256: "/avatars/office/256/marker.png",              path512: "/avatars/office/512/marker.png" },
  { id: "name_badge",          label: "Name Badge",          path: "/avatars/office/128/name_badge.png",          path64: "/avatars/office/64/name_badge.png",          path128: "/avatars/office/128/name_badge.png",          path256: "/avatars/office/256/name_badge.png",          path512: "/avatars/office/512/name_badge.png" },
  { id: "notebook",            label: "Notebook",            path: "/avatars/office/128/notebook.png",            path64: "/avatars/office/64/notebook.png",            path128: "/avatars/office/128/notebook.png",            path256: "/avatars/office/256/notebook.png",            path512: "/avatars/office/512/notebook.png" },
  { id: "office_desk",         label: "Office Desk",         path: "/avatars/office/128/office_desk.png",         path64: "/avatars/office/64/office_desk.png",         path128: "/avatars/office/128/office_desk.png",         path256: "/avatars/office/256/office_desk.png",         path512: "/avatars/office/512/office_desk.png" },
  { id: "out_tray",            label: "Out Tray",            path: "/avatars/office/128/out_tray.png",            path64: "/avatars/office/64/out_tray.png",            path128: "/avatars/office/128/out_tray.png",            path256: "/avatars/office/256/out_tray.png",            path512: "/avatars/office/512/out_tray.png" },
  { id: "paper_cutter",        label: "Paper Cutter",        path: "/avatars/office/128/paper_cutter.png",        path64: "/avatars/office/64/paper_cutter.png",        path128: "/avatars/office/128/paper_cutter.png",        path256: "/avatars/office/256/paper_cutter.png",        path512: "/avatars/office/512/paper_cutter.png" },
  { id: "paper_shredder",      label: "Paper Shredder",      path: "/avatars/office/128/paper_shredder.png",      path64: "/avatars/office/64/paper_shredder.png",      path128: "/avatars/office/128/paper_shredder.png",      path256: "/avatars/office/256/paper_shredder.png",      path512: "/avatars/office/512/paper_shredder.png" },
  { id: "pen",                 label: "Pen",                 path: "/avatars/office/128/pen.png",                 path64: "/avatars/office/64/pen.png",                 path128: "/avatars/office/128/pen.png",                 path256: "/avatars/office/256/pen.png",                 path512: "/avatars/office/512/pen.png" },
  { id: "pencil",              label: "Pencil",              path: "/avatars/office/128/pencil.png",              path64: "/avatars/office/64/pencil.png",              path128: "/avatars/office/128/pencil.png",              path256: "/avatars/office/256/pencil.png",              path512: "/avatars/office/512/pencil.png" },
  { id: "printer",             label: "Printer",             path: "/avatars/office/128/printer.png",             path64: "/avatars/office/64/printer.png",             path128: "/avatars/office/128/printer.png",             path256: "/avatars/office/256/printer.png",             path512: "/avatars/office/512/printer.png" },
  { id: "projector",           label: "Projector",           path: "/avatars/office/128/projector.png",           path64: "/avatars/office/64/projector.png",           path128: "/avatars/office/128/projector.png",           path256: "/avatars/office/256/projector.png",           path512: "/avatars/office/512/projector.png" },
  { id: "push_pin",            label: "Push Pin",            path: "/avatars/office/128/push_pin.png",            path64: "/avatars/office/64/push_pin.png",            path128: "/avatars/office/128/push_pin.png",            path256: "/avatars/office/256/push_pin.png",            path512: "/avatars/office/512/push_pin.png" },
  { id: "ruler",               label: "Ruler",               path: "/avatars/office/128/ruler.png",               path64: "/avatars/office/64/ruler.png",               path128: "/avatars/office/128/ruler.png",               path256: "/avatars/office/256/ruler.png",               path512: "/avatars/office/512/ruler.png" },
  { id: "scissors",            label: "Scissors",            path: "/avatars/office/128/scissors.png",            path64: "/avatars/office/64/scissors.png",            path128: "/avatars/office/128/scissors.png",            path256: "/avatars/office/256/scissors.png",            path512: "/avatars/office/512/scissors.png" },
  { id: "stapler",             label: "Stapler",             path: "/avatars/office/128/stapler.png",             path64: "/avatars/office/64/stapler.png",             path128: "/avatars/office/128/stapler.png",             path256: "/avatars/office/256/stapler.png",             path512: "/avatars/office/512/stapler.png" },
  { id: "sticky_notes",        label: "Sticky Notes",        path: "/avatars/office/128/sticky_notes.png",        path64: "/avatars/office/64/sticky_notes.png",        path128: "/avatars/office/128/sticky_notes.png",        path256: "/avatars/office/256/sticky_notes.png",        path512: "/avatars/office/512/sticky_notes.png" },
  { id: "tape_dispenser",      label: "Tape Dispenser",      path: "/avatars/office/128/tape_dispenser.png",      path64: "/avatars/office/64/tape_dispenser.png",      path128: "/avatars/office/128/tape_dispenser.png",      path256: "/avatars/office/256/tape_dispenser.png",      path512: "/avatars/office/512/tape_dispenser.png" },
  { id: "thumb_drive",         label: "Thumb Drive",         path: "/avatars/office/128/thumb_drive.png",         path64: "/avatars/office/64/thumb_drive.png",         path128: "/avatars/office/128/thumb_drive.png",         path256: "/avatars/office/256/thumb_drive.png",         path512: "/avatars/office/512/thumb_drive.png" },
  { id: "wall_clock",          label: "Wall Clock",          path: "/avatars/office/128/wall_clock.png",          path64: "/avatars/office/64/wall_clock.png",          path128: "/avatars/office/128/wall_clock.png",          path256: "/avatars/office/256/wall_clock.png",          path512: "/avatars/office/512/wall_clock.png" },
  { id: "whiteboard",          label: "Whiteboard",          path: "/avatars/office/128/whiteboard.png",          path64: "/avatars/office/64/whiteboard.png",          path128: "/avatars/office/128/whiteboard.png",          path256: "/avatars/office/256/whiteboard.png",          path512: "/avatars/office/512/whiteboard.png" },
  { id: "whiteout",            label: "Whiteout",            path: "/avatars/office/128/whiteout.png",            path64: "/avatars/office/64/whiteout.png",            path128: "/avatars/office/128/whiteout.png",            path256: "/avatars/office/256/whiteout.png",            path512: "/avatars/office/512/whiteout.png" },
] as const satisfies readonly OfficeAvatar[]

export type OfficeAvatarId = (typeof OFFICE_AVATARS)[number]["id"]

export function officeAvatarPath(id: OfficeAvatarId | string, size: 64 | 128 | 256 | 512 = 128): string | null {
  const avatar = OFFICE_AVATARS.find((item) => item.id === id)
  if (!avatar) return null
  return avatar[`path${size}` as keyof OfficeAvatar] as string
}
